---
- hosts: kubernetes_nodes
  become: true
  tasks:
    - name: Install Kubernetes dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Kubernetes GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Disable swap
      sysctl:
        name: vm.swappiness
        value: 0
        state: present
        sysctl_set: yes

    - name: Update sysctl settings
      lineinfile:
        dest: /etc/sysctl.conf
        regexp: '^#?net.bridge.bridge-nf-call-iptables'
        line: 'net.bridge.bridge-nf-call-iptables = 1'
        state: present

    - name: Enable and start kubelet service
      service:
        name: kubelet
        enabled: yes
        state: started
